sudo: false
language: ruby
rvm:
  - "2.2"

before_script:
  # Generate a virtual framebuffer X server to collect browser windows
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

  # Wait for Xvfb to start
  - sleep 3

script:
  - ./test.sh

notifications:
  email:
    recipients:
      - todd@twolfson.com
    on_success: change
    on_failure: change
